samples:
 SRR099960

ref: "/path/to/supporting_files/hg38/hg38.fa" 
known_sites: "/path/to/supporting_files/hg38/Homo_sapiens_assembly38.dbsnp138.vcf"
aligned_reads: "/path/to/aligned_reads"
reads: "/path/to/reads"
results: "/path/to/results"
data: "/path/to/data"
trimmed_reads: "/path/to/trimmed_reads"
mutation: "/path/to/PTPN4_Q180Ter_chr2.bed"
dataSources: "/path/to/dataSources/funcotator_dataSources.v1.8.hg38.20230908g"
